name = "nbac"
main = "src/worker.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-03-20"
routes = [
  { pattern = "ml.videreproject.com", custom_domain = true }
]

[[d1_databases]]
binding = "D1"
database_name = "nbac-model"
database_id = "ef89eb5f-e784-48d2-9486-b2b494281f86"
